
export const projectJsonData = {
    "beulah" : { "title": "Beulah Park", "year": "2002-2008", "id": 0 , "background-image": "./beulah.png"}, 
    "winticket": { "title": "Winticket", "year": "2002-2006", "id": 1 ,"background-image": "./winticket.png"},
    "cms": { "title": "CMS", "year": "2002-2008","id": 2 ,"background-image": "./cms.png"}, 
    "report": {"title": "Reporting", "year": "2002-2008","id": 3 ,"background-image": "./reporting.png"}, 
    "net": {"title": "Networking", "year": "2002-2008","id": 4 ,"background-image": "./networking.png"},
    "nhc": {"title": "NHCQualify", "year": "2008","id": 5 ,"background-image": "./nhcqualify.png"}, 
    "bet": {"title": "Betpad", "year": "2007-2008","id": 6 ,"background-image": "./betpad.jpg"}, 
    "xl": {"title": "XLPharmacy", "year": "2009","id": 7 ,"background-image": "./xlpharmacy.png"}, 
    "whc": {"title": "WHChamp", "year": "2010","id": 8 ,"background-image": "./whchamp.png"}, 
    "tqha": {"title": "TQHA", "year": "2010","id": 9 ,"background-image": "./tqha.png"}, 
    "dark": {"title": "Darkhorsebet", "year": "2010-2012","id": 10 ,"background-image": "./darkhorse.png"},
    "kai": {"title": "Kairos", "year": "2010-2011","id": 11 ,"background-image": "./kairos.png"}, 
    "ebet": {"title": "eBet Technologies", "year": "2011-2019","id": 12 ,"background-image": "./ebet.png"}, 
    "bat": {"title": "BataviaBets", "year": "2011-2019","id": 13 ,"background-image": "./bataviabets.png"}, 
    "fin": {"title": "FingerLakes", "year": "2011-2019","id": 14 ,"background-image": "./fingerlakes.png"}, 
    "sgr": {"title": "SaratogaBets", "year": "2011-2019","id": 15 ,"background-image": "./saratoga.png"},
    "hpb": {"title": "Horseplayersbet", "year": "2011-2019","id": 16 ,"background-image": "./horseplayers.png"}, 
    "ruw": {"title": "Raceuwin", "year": "2011-2019","id": 17 ,"background-image": "./raceuwin.png"}, 
    "wlr": {"title": "Wager Live Racing", "year": "2011-2019","id": 18 ,"background-image": "./wlr.png"}, 
    "yon": {"title": "Empirecitybets", "year": "2011-2019","id": 19 ,"background-image": "./yonkers.png"}, 
    "mo": {"title": "Mutuels Online", "year": "2011-2019","id": 20 ,"background-image": "./mutuels.png"},
    "ghc": {"title": "Greyhoundchannel", "year": "2011-2019","id": 21 ,"background-image": "./ghc.png"},
    "kno": {"title": "Knobbe Martens", "year": "2019","id": 22 ,"background-image": "./knobbe.png"}, 
    "wfs": {"title": "World Fuel Services", "year": "2019","id": 23 ,"background-image": "./wfs.png"}, 
    "qa": {"title": "QA Automation", "year": "2019","id": 24 ,"background-image":  "./qa.png"}, 
    "md": {"title": "Sociedad M&D", "year": "2024","id": 25 ,"background-image": "sociedad.png"}
};